services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/filmplace:z
      # Зберігаємо файл SQLite3 між перезапусками
      - sqlite_data:/filmplace/sqlite

volumes:
  sqlite_data: