# Generated by Django 6.1.1 on 2026-09-29 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_options_remove_booking_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Початок сеансу')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Кінець сеансу')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна квитка')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеанси',
                'ordering': ['start_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Бронювання', 'verbose_name_plural': 'Бронювання'},
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_booking_per_seat_and_showtime',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='price',
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AddField(
            model_name='showtime',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='booking.movie'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='showtime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.showtime'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('showtime', 'row', 'place'), name='unique_booking_per_seat_and_showtime'),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='movie',
        ),
    ]
