# Generated by Django 6.1.1 on 2026-09-29 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_showtime_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва залу')),
                ('rows', models.PositiveIntegerField(verbose_name='Кількість рядів')),
                ('seats_per_row', models.PositiveIntegerField(verbose_name='Місць у ряду')),
            ],
            options={
                'verbose_name': 'Кінозал',
                'verbose_name_plural': 'Кінозали',
            },
        ),
        migrations.AddField(
            model_name='showtime',
            name='hall',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='booking.hall', verbose_name='Зал'),
            preserve_default=False,
        ),
    ]
